"""create patient table

Revision ID: 2afc91c5b3e8
Revises: 
Create Date: 2025-04-27 14:29:08.196334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2afc91c5b3e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anrede', sa.String(length=10), nullable=True),
    sa.Column('vorname', sa.String(length=100), nullable=False),
    sa.Column('nachname', sa.String(length=100), nullable=False),
    sa.Column('strasse', sa.String(length=255), nullable=True),
    sa.Column('plz', sa.String(length=10), nullable=True),
    sa.Column('ort', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefon', sa.String(length=50), nullable=True),
    sa.Column('hausarzt', sa.String(length=255), nullable=True),
    sa.Column('krankenkasse', sa.String(length=100), nullable=True),
    sa.Column('krankenversicherungsnummer', sa.String(length=50), nullable=True),
    sa.Column('geburtsdatum', sa.Date(), nullable=True),
    sa.Column('diagnose', sa.String(length=50), nullable=True),
    sa.Column('vertraege_unterschrieben', sa.Boolean(), nullable=True),
    sa.Column('psychotherapeutische_sprechstunde', sa.Boolean(), nullable=True),
    sa.Column('startdatum', sa.Date(), nullable=True),
    sa.Column('erster_therapieplatz_am', sa.Date(), nullable=True),
    sa.Column('funktionierender_therapieplatz_am', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'SEARCHING', 'IN_THERAPY', 'THERAPY_COMPLETED', 'SEARCH_ABORTED', 'THERAPY_ABORTED', name='patientstatus'), nullable=True),
    sa.Column('empfehler_der_unterstuetzung', sa.Text(), nullable=True),
    sa.Column('zeitliche_verfuegbarkeit', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raeumliche_verfuegbarkeit', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verkehrsmittel', sa.String(length=50), nullable=True),
    sa.Column('offen_fuer_gruppentherapie', sa.Boolean(), nullable=True),
    sa.Column('offen_fuer_diga', sa.Boolean(), nullable=True),
    sa.Column('letzter_kontakt', sa.Date(), nullable=True),
    sa.Column('psychotherapieerfahrung', sa.Boolean(), nullable=True),
    sa.Column('stationaere_behandlung', sa.Boolean(), nullable=True),
    sa.Column('berufliche_situation', sa.Text(), nullable=True),
    sa.Column('familienstand', sa.String(length=50), nullable=True),
    sa.Column('aktuelle_psychische_beschwerden', sa.Text(), nullable=True),
    sa.Column('beschwerden_seit', sa.Date(), nullable=True),
    sa.Column('bisherige_behandlungen', sa.Text(), nullable=True),
    sa.Column('relevante_koerperliche_erkrankungen', sa.Text(), nullable=True),
    sa.Column('aktuelle_medikation', sa.Text(), nullable=True),
    sa.Column('aktuelle_belastungsfaktoren', sa.Text(), nullable=True),
    sa.Column('unterstuetzungssysteme', sa.Text(), nullable=True),
    sa.Column('anlass_fuer_die_therapiesuche', sa.Text(), nullable=True),
    sa.Column('erwartungen_an_die_therapie', sa.Text(), nullable=True),
    sa.Column('therapieziele', sa.Text(), nullable=True),
    sa.Column('fruehere_therapieerfahrungen', sa.Text(), nullable=True),
    sa.Column('ausgeschlossene_therapeuten', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bevorzugtes_therapeutengeschlecht', sa.Enum('MALE', 'FEMALE', 'ANY', name='therapistgenderpreference'), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='patient_service'
    )
    op.create_index(op.f('ix_patient_service_patients_id'), 'patients', ['id'], unique=False, schema='patient_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_service_patients_id'), table_name='patients', schema='patient_service')
    op.drop_table('patients', schema='patient_service')
    # ### end Alembic commands ###
